using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Text.Json;

namespace FocusDimmer.Services
{
    public class LocalizationService : INotifyPropertyChanged
    {
        public string AppTitle { get; set; } = "Focus Dimmer";
        public string BadgeAllMonitors { get; set; } = "ALL MONITORS";
        public string BannerText { get; set; } = "Get Pro Version to unlock Multi-Monitor & Color settings!";
        public string BtnAddBright { get; set; } = "Add to Always Bright List";
        public string BtnAddDark { get; set; } = "Add to Always Dark List";
        public string BtnAddIgnore { get; set; } = "Add to Ignore List";
        public string BtnAddProcessRule { get; set; } = "Add Process Rule";
        public string BtnBrowse { get; set; } = "Browse...";
        public string BtnCancel { get; set; } = "Cancel";
        public string BtnClose { get; set; } = "Close to Tray";
        public string BtnDebug { get; set; } = "Inspector";
        public string BtnMigrationInfo { get; set; } = "Migration Info";
        public string BtnMinimize { get; set; } = "Minimize";
        public string BtnRefresh { get; set; } = "Refresh";
        public string BtnSelect { get; set; } = "Select";
        public string BtnUpgradePro { get; set; } = "Upgrade to Pro";
        public string CheckAdmin { get; set; } = "Run as Administrator";
        public string CheckAutoStart { get; set; } = "Auto Start";
        public string CheckCloseToTray { get; set; } = "Minimize to system tray on close (×)";
        public string CheckDimDesktopOnly { get; set; } = "Display all windows brightly";
        public string CheckDimEntirely { get; set; } = "Dim entire monitor when inactive";
        public string CheckDimOnIdle { get; set; } = "Dim automatically when idle";
        public string CheckDimWhenIdle { get; set; } = "Dim entire monitor when idle";
        public string CheckTaskbar { get; set; } = "Always keep Taskbar bright";
        public string CheckTightFrame { get; set; } = "Fit dimming area tightly to window frame";
        public string CheckTopmost { get; set; } = "Always keep Picture-in-Picture bright";
        public string DebugClass { get; set; } = "Class";
        public string DebugFlags { get; set; } = "Flags";
        public string DebugLayered { get; set; } = "Layered";
        public string DebugMouse { get; set; } = "Mouse";
        public string DebugNoActivate { get; set; } = "No Activate";
        public string DebugProcess { get; set; } = "Process";
        public string DebugRect { get; set; } = "Rect";
        public string DebugStatusClick { get; set; } = "Click to freeze";
        public string DebugStatusSelect { get; set; } = "Select from the list";
        public string DebugTitle { get; set; } = "Title";
        public string DebugToolWindow { get; set; } = "Tool Window";
        public string DebugTransparent { get; set; } = "Transparent";
        public string DefaultPresetName { get; set; } = "Default";
        public string DescMultiMonitorPro { get; set; } = "Upgrade to Pro to dim and customize multiple displays simultaneously.";
        public string HeaderAdvancedBehavior { get; set; } = "Advanced Behavior";
        public string HeaderAnimation { get; set; } = "ANIMATION SETTINGS";
        public string HeaderBehavior { get; set; } = "Behavior Settings";
        public string HeaderExclusionLists { get; set; } = "EXCLUSION LISTS (Process)";
        public string HeaderGlobalSettings { get; set; } = "Global Settings";
        public string HeaderLanguage { get; set; } = "Language";
        public string HeaderMultiMonitorPro { get; set; } = "Multi-Display Dimming";
        public string HeaderOverlay { get; set; } = "OVERLAY SETTINGS";
        public string HeaderPreset { get; set; } = "PRESETS";
        public string HeaderStartup { get; set; } = "Startup:";
        public string LabelAlwaysBright { get; set; } = "Always bright (Process):";
        public string LabelAlwaysDark { get; set; } = "Always dark (Process):";
        public string LabelAppList { get; set; } = "Don't dim when active (Process):";
        public string LabelAssociatedProcesses { get; set; } = "Associated Processes:";
        public string LabelBrighten { get; set; } = "Fade Out";
        public string LabelColor { get; set; } = "Overlay Color";
        public string LabelCopyright { get; set; } = "Copyright © 2025 Focus Dimmer. All rights reserved.";
        public string LabelDarken { get; set; } = "Fade In";
        public string LabelDarker { get; set; } = "Darken";
        public string LabelDefault { get; set; } = "(Default)";
        public string LabelDuration { get; set; } = "Animation Time";
        public string LabelIdleOpacity { get; set; } = "Idle Opacity";
        public string LabelIdleTime { get; set; } = "Idle time";
        public string LabelLighter { get; set; } = "Brighten";
        public string LabelLinkMonitors { get; set; } = "Link All Displays";
        public string LabelMargin { get; set; } = "Margin";
        public string LabelOpacity { get; set; } = "Opacity";
        public string LabelOpacityLong { get; set; } = "Overlay Opacity";
        public string LabelProcessSwitch { get; set; } = "Auto-switch when process is active:";
        public string LabelToggle { get; set; } = "ON/OFF";
        public string LabelWait { get; set; } = "Wait Time";
        public string MenuExit { get; set; } = "Exit";
        public string MenuRename { get; set; } = "Rename";
        public string MigrationBannerLink { get; set; } = "Migrate to Latest Version 🚀";
        public string MigrationBannerText { get; set; } = "We have unified the app configuration for continued updates.\nExisting Pro users, please uninstall the old Focus Dimmer after installing this unified version.";
        public string MigrationGuideText { get; set; } = "Thank you for purchasing this app. To ensure smoother updates in the future, we have decided to unify the app structure into a \"Unified Version\".\n\nFuture Pro features will be provided as an \"Add-on (In-App Purchase)\" in the Unified Version. However, if you have already purchased this Pro version, you can continue to use Pro features for free by following these steps:\n\n1. Install the new \"Unified Version\" while keeping this app (Pro version) installed.\n\n2. Confirm that the Pro features are automatically unlocked in the Unified Version.\n\n3. After confirming the unlock, you can safely uninstall this app.\n\nYou can continue to use this app as is, but the store page will be hidden from non-purchasers, and updates will stop. To access the latest features, we strongly recommend migrating to the Unified Version.\n\nWe apologize for any inconvenience and appreciate your continued support.";
        public string MigrationOpenStorePage { get; set; } = "Open Unified Version Store Page";
        public string MsgConfirmDeletePreset { get; set; } = "Delete this preset?";
        public string MsgEnterPresetName { get; set; } = "Enter preset name:";
        public string MsgProRequired { get; set; } = "This feature requires the Pro version.\nWould you like to view it in the Store?";
        public string MsgPurchaseFailedManual { get; set; } = "Purchase Failed.\nStatus: {0}\nError: {1}\n\nDo you want to open the Store Page manually?";
        public string MsgPurchaseSuccess { get; set; } = "Thank you for your purchase!\nPro features unlocked.";
        public string MsgStartedInBackground { get; set; } = "Started in background.";
        public string MsgStartupDisabledByUser { get; set; } = "Startup is disabled in Windows Settings or Task Manager.\nPlease enable Focus Dimmer in Windows 'Startup Apps' settings.";
        public string NavExclusions { get; set; } = "Exclusions";
        public string NavGeneral { get; set; } = "General";
        public string NavHotkeys { get; set; } = "Hotkeys";
        public string NavMonitors { get; set; } = "Monitors";
        public string NavPresets { get; set; } = "Presets";
        public string NewPresetName { get; set; } = "New Preset";
        public string SearchPlaceholder { get; set; } = "Search processes...";
        public string SubHeaderGeneral { get; set; } = "App startup, behavior and language settings.";
        public string SubHeaderGlobalSettings { get; set; } = "These settings apply to all connected monitors.";
        public string SubHeaderHotkeys { get; set; } = "Configure keyboard shortcuts to quickly control dimming.";
        public string SubHeaderLanguage { get; set; } = "Choose display language";
        public string TitleColorPicker { get; set; } = "Color Picker";
        public string TitleConfirm { get; set; } = "Confirm";
        public string TitleError { get; set; } = "Error";
        public string TitleInspector { get; set; } = "Focus Dimmer Inspector";
        public string TitleMigrationGuide { get; set; } = "Migration Guide";
        public string TitlePurchaseError { get; set; } = "Purchase Error";
        public string TitleSelectAction { get; set; } = "Select Action";
        public string TitleSelectProcess { get; set; } = "Select App";
        public string TitleSuccess { get; set; } = "Success";
        public string TooltipAddPreset { get; set; } = "Save current settings as new preset";
        public string TooltipAlwaysDark { get; set; } = "Add overlay processes from other apps (e.g., GeForce Experience) that may cause unexpected bright regions.";
        public string TooltipDebugInspector { get; set; } = "Inspect all windows under cursor, including transparent ones.";
        public string TooltipDeletePreset { get; set; } = "Delete selected preset";
        public string TooltipDimDesktopOnly { get; set; } = "Only the desktop area will be dimmed. Margin function disabled.";
        public string TooltipDimEntirely { get; set; } = "Prioritized over other brightness options.";
        public string TooltipDimWhenIdle { get; set; } = "Prioritized over other brightness options.";
        public string TooltipEditPreset { get; set; } = "Edit preset name";
        public string TooltipLinkMonitors { get; set; } = "When enabled, changes to one display will automatically apply to all displays.";
        public string TooltipSetAsDefault { get; set; } = "Set as Default Preset";
        public string TooltipWait { get; set; } = "Time from when the window becomes active until the animation starts.";
        public string WindowSelectApp { get; set; } = "Select App";

        public string? this[string propertyName]
        {
            get
            {
                var prop = this.GetType().GetProperty(propertyName);
                return prop?.GetValue(this)?.ToString();
            }
        }

        public void UpdateLanguage(string langCode)
        {
            SetDefaultEnglish();
            string exePath = AppDomain.CurrentDomain.BaseDirectory;
            string langPath = System.IO.Path.Combine(exePath, "Languages", $"{langCode}.json");
            if (File.Exists(langPath))
            {
                try
                {
                    var options = new JsonSerializerOptions { AllowTrailingCommas = true, ReadCommentHandling = JsonCommentHandling.Skip };
                    string json = File.ReadAllText(langPath);
                    var dict = JsonSerializer.Deserialize<Dictionary<string, string>>(json, options);
                    if (dict != null)
                    {
                        var properties = this.GetType().GetProperties();
                        foreach (var kvp in dict)
                        {
                            var prop = properties.FirstOrDefault(p => p.Name == kvp.Key);
                            if (prop != null && prop.CanWrite) prop.SetValue(this, kvp.Value);
                        }
                    }
                }
                catch { }
            }
            else if (langCode == "ja") SetDefaultJapanese();
            OnProp(null);
        }

        private void SetDefaultEnglish()
        {
            AppTitle = "Focus Dimmer";
            BadgeAllMonitors = "ALL MONITORS";
            BannerText = "Get Pro Version to unlock Multi-Monitor & Color settings!";
            BtnAddBright = "Add to Always Bright List";
            BtnAddDark = "Add to Always Dark List";
            BtnAddIgnore = "Add to Ignore List";
            BtnAddProcessRule = "Add Process Rule";
            BtnBrowse = "Browse...";
            BtnCancel = "Cancel";
            BtnClose = "Close to Tray";
            BtnDebug = "Inspector";
            BtnMigrationInfo = "Migration Info";
            BtnMinimize = "Minimize";
            BtnRefresh = "Refresh";
            BtnSelect = "Select";
            BtnUpgradePro = "Upgrade to Pro";
            CheckAdmin = "Run as Administrator";
            CheckAutoStart = "Auto Start";
            CheckCloseToTray = "Minimize to system tray on close (×)";
            CheckDimDesktopOnly = "Display all windows brightly";
            CheckDimEntirely = "Dim entire monitor when inactive";
            CheckDimOnIdle = "Dim automatically when idle";
            CheckDimWhenIdle = "Dim entire monitor when idle";
            CheckTaskbar = "Always keep Taskbar bright";
            CheckTightFrame = "Fit dimming area tightly to window frame";
            CheckTopmost = "Always keep Picture-in-Picture bright";
            DebugClass = "Class";
            DebugFlags = "Flags";
            DebugLayered = "Layered";
            DebugMouse = "Mouse";
            DebugNoActivate = "No Activate";
            DebugProcess = "Process";
            DebugRect = "Rect";
            DebugStatusClick = "Click to freeze";
            DebugStatusSelect = "Select from the list";
            DebugTitle = "Title";
            DebugToolWindow = "Tool Window";
            DebugTransparent = "Transparent";
            DefaultPresetName = "Default";
            DescMultiMonitorPro = "Upgrade to Pro to dim and customize multiple displays simultaneously.";
            HeaderAdvancedBehavior = "Advanced Behavior";
            HeaderAnimation = "ANIMATION SETTINGS";
            HeaderBehavior = "Behavior Settings";
            HeaderExclusionLists = "EXCLUSION LISTS (Process)";
            HeaderGlobalSettings = "Global Settings";
            HeaderLanguage = "Language";
            HeaderMultiMonitorPro = "Multi-Display Dimming";
            HeaderOverlay = "OVERLAY SETTINGS";
            HeaderPreset = "PRESETS";
            HeaderStartup = "Startup:";
            LabelAlwaysBright = "Always bright (Process):";
            LabelAlwaysDark = "Always dark (Process):";
            LabelAppList = "Don't dim when active (Process):";
            LabelAssociatedProcesses = "Associated Processes:";
            LabelBrighten = "Fade Out";
            LabelColor = "Overlay Color";
            LabelCopyright = "Copyright © 2025 Focus Dimmer. All rights reserved.";
            LabelDarken = "Fade In";
            LabelDarker = "Darken";
            LabelDefault = "(Default)";
            LabelDuration = "Animation Time";
            LabelIdleOpacity = "Idle Opacity";
            LabelIdleTime = "Idle time";
            LabelLighter = "Brighten";
            LabelLinkMonitors = "Link All Displays";
            LabelMargin = "Margin";
            LabelOpacity = "Opacity";
            LabelOpacityLong = "Overlay Opacity";
            LabelProcessSwitch = "Auto-switch when process is active:";
            LabelToggle = "ON/OFF";
            LabelWait = "Wait Time";
            MenuExit = "Exit";
            MenuRename = "Rename";
            MigrationBannerLink = "Migrate to Latest Version 🚀";
            MigrationBannerText = "We have unified the app configuration for continued updates.\nExisting Pro users, please uninstall the old Focus Dimmer after installing this unified version.";
            MigrationGuideText = "Thank you for purchasing this app. To ensure smoother updates in the future, we have decided to unify the app structure into a \"Unified Version\".\n\nFuture Pro features will be provided as an \"Add-on (In-App Purchase)\" in the Unified Version. However, if you have already purchased this Pro version, you can continue to use Pro features for free by following these steps:\n\n1. Install the new \"Unified Version\" while keeping this app (Pro version) installed.\n\n2. Confirm that the Pro features are automatically unlocked in the Unified Version.\n\n3. After confirming the unlock, you can safely uninstall this app.\n\nYou can continue to use this app as is, but the store page will be hidden from non-purchasers, and updates will stop. To access the latest features, we strongly recommend migrating to the Unified Version.\n\nWe apologize for any inconvenience and appreciate your continued support.";
            MigrationOpenStorePage = "Open Unified Version Store Page";
            MsgConfirmDeletePreset = "Delete this preset?";
            MsgEnterPresetName = "Enter preset name:";
            MsgProRequired = "This feature requires the Pro version.\nWould you like to view it in the Store?";
            MsgPurchaseFailedManual = "Purchase Failed.\nStatus: {0}\nError: {1}\n\nDo you want to open the Store Page manually?";
            MsgPurchaseSuccess = "Thank you for your purchase!\nPro features unlocked.";
            MsgStartedInBackground = "Started in background.";
            MsgStartupDisabledByUser = "Startup is disabled in Windows Settings or Task Manager.\nPlease enable Focus Dimmer in Windows 'Startup Apps' settings.";
            NavExclusions = "Exclusions";
            NavGeneral = "General";
            NavHotkeys = "Hotkeys";
            NavMonitors = "Monitors";
            NavPresets = "Presets";
            NewPresetName = "New Preset";
            SearchPlaceholder = "Search processes...";
            SubHeaderGeneral = "App startup, behavior and language settings.";
            SubHeaderGlobalSettings = "These settings apply to all connected monitors.";
            SubHeaderHotkeys = "Configure keyboard shortcuts to quickly control dimming.";
            SubHeaderLanguage = "Choose display language";
            TitleColorPicker = "Color Picker";
            TitleConfirm = "Confirm";
            TitleError = "Error";
            TitleInspector = "Focus Dimmer Inspector";
            TitleMigrationGuide = "Migration Guide";
            TitlePurchaseError = "Purchase Error";
            TitleSelectAction = "Select Action";
            TitleSelectProcess = "Select App";
            TitleSuccess = "Success";
            TooltipAddPreset = "Save current settings as new preset";
            TooltipAlwaysDark = "Add overlay processes from other apps (e.g., GeForce Experience) that may cause unexpected bright regions.";
            TooltipDebugInspector = "Inspect all windows under cursor, including transparent ones.";
            TooltipDeletePreset = "Delete selected preset";
            TooltipDimDesktopOnly = "Only the desktop area will be dimmed. Margin function disabled.";
            TooltipDimEntirely = "Prioritized over other brightness options.";
            TooltipDimWhenIdle = "Prioritized over other brightness options.";
            TooltipEditPreset = "Edit preset name";
            TooltipLinkMonitors = "When enabled, changes to one display will automatically apply to all displays.";
            TooltipSetAsDefault = "Set as Default Preset";
            TooltipWait = "Time from when the window becomes active until the animation starts.";
            WindowSelectApp = "Select App";
        }

        private void SetDefaultJapanese()
        {
            AppTitle = "Focus Dimmer";
            BadgeAllMonitors = "モニター共通";
            BannerText = "Pro版を取得してマルチモニターや色設定を解除！";
            BtnAddBright = "常に明るくするリストに追加する";
            BtnAddDark = "常に暗くするリストに追加する";
            BtnAddIgnore = "除外リストに追加する";
            BtnAddProcessRule = "プロセスルールを追加";
            BtnBrowse = "ファイル参照...";
            BtnCancel = "キャンセル";
            BtnClose = "タスクトレイに閉じる";
            BtnDebug = "インスペクター";
            BtnMigrationInfo = "移行情報";
            BtnMinimize = "最小化";
            BtnRefresh = "更新";
            BtnSelect = "選択";
            BtnUpgradePro = "PROにアップグレード";
            CheckAdmin = "管理者として実行";
            CheckAutoStart = "自動起動";
            CheckCloseToTray = "閉じるボタン（×）でタスクトレイに最小化する";
            CheckDimDesktopOnly = "全てのウィンドウを明るく表示する";
            CheckDimEntirely = "このモニタが非アクティブ時は全体を暗くする";
            CheckDimOnIdle = "操作がない時に自動で暗くする";
            CheckDimWhenIdle = "操作がない状態の時に全体を暗くする";
            CheckTaskbar = "タスクバーを常に明るくする";
            CheckTightFrame = "ウィンドウの枠に減光範囲をぴったり合わせる";
            CheckTopmost = "ピクチャー・イン・ピクチャーを常に明るくする";
            DebugClass = "クラス";
            DebugFlags = "属性";
            DebugLayered = "レイヤード(Layered)";
            DebugMouse = "マウス";
            DebugNoActivate = "No Activate";
            DebugProcess = "プロセス";
            DebugRect = "領域";
            DebugStatusClick = "クリックしてフリーズ";
            DebugStatusSelect = "リストから選択してください";
            DebugTitle = "タイトル";
            DebugToolWindow = "ツールウィンドウ";
            DebugTransparent = "透過(Transparent)";
            DefaultPresetName = "デフォルト";
            DescMultiMonitorPro = "接続された複数のディスプレイを個別に減光・連動制御するにはPRO版が必要です。";
            HeaderAdvancedBehavior = "高度な動作設定";
            HeaderAnimation = "アニメーション設定";
            HeaderBehavior = "動作設定";
            HeaderExclusionLists = "除外設定 (プロセス)";
            HeaderGlobalSettings = "共通設定";
            HeaderLanguage = "言語 / Language";
            HeaderMultiMonitorPro = "マルチモニター減光制御";
            HeaderOverlay = "オーバーレイ設定";
            HeaderPreset = "プリセット";
            HeaderStartup = "起動設定:";
            LabelAlwaysBright = "常に明るくするプロセス:";
            LabelAlwaysDark = "常に暗くするプロセス:";
            LabelAppList = "アクティブ時に減光させないプロセス:";
            LabelAssociatedProcesses = "関連付けられたプロセス:";
            LabelBrighten = "フェードアウト";
            LabelColor = "オーバーレイの色";
            LabelCopyright = "Copyright © 2025 Focus Dimmer. All rights reserved.";
            LabelDarken = "フェードイン";
            LabelDarker = "暗くする";
            LabelDefault = "(既定)";
            LabelDuration = "アニメーション時間";
            LabelIdleOpacity = "アイドル時の不透明度";
            LabelIdleTime = "無操作時間";
            LabelLighter = "明るくする";
            LabelLinkMonitors = "全ディスプレイ連動";
            LabelMargin = "余白";
            LabelOpacity = "減光レベル";
            LabelOpacityLong = "オーバーレイの不透明度";
            LabelProcessSwitch = "プロセス実行時に自動切替:";
            LabelToggle = "ON/OFF";
            LabelWait = "待機時間";
            MenuExit = "アプリを終了";
            MenuRename = "名前を変更";
            MigrationBannerLink = "統合版(最新)へ無料移行 🚀";
            MigrationBannerText = "今後のアップデートを継続するため、アプリ構成を統合しました。\n現在のPro版ユーザー様は、本統合版をインストール後、古いFocusDimmerはアンインストールしてください。";
            MigrationGuideText = "この度は本アプリをご購入いただき、誠にありがとうございます。 今後、よりスムーズにアップデートを継続していくため、勝手ながらアプリの構成を「統合版」へと一本化させていただくこととなりました。\n\n今後のPro版機能は、統合版における「アドオン（アプリ内課金）」として提供されますが、すでに本Pro版をご購入いただいている皆様は、以下の手順で引き続きPro機能を無料でご利用いただけます。\n\n1. 本アプリ（Pro版）をインストールした状態のまま、新しい「統合版」をインストールしてください。\n\n2. 統合版にてPro機能が自動的にアンロックされていることを確認してください。\n\n3. アンロックの確認後は、本アプリをアンインストールしていただいて問題ありません。\n\nなお、本アプリをそのまま使い続けることも可能ですが、今後のストアページはご購入者様以外には非公開となり、ページの更新も停止いたします。最新の機能をご利用いただくためにも、ぜひ統合版への移行をお願い申し上げます。\n\nご不便をおかけいたしますが、今後ともよろしくお願いいたします。";
            MigrationOpenStorePage = "統合版のストアページを開く";
            MsgConfirmDeletePreset = "このプリセットを削除しますか？";
            MsgEnterPresetName = "プリセット名を入力:";
            MsgProRequired = "この機能はPro版のみ使用可能です。\nストアでPro版を確認しますか？";
            MsgPurchaseFailedManual = "購入に失敗しました。\n状態: {0}\nエラー: {1}\n\nストアページを手動で開きますか？";
            MsgPurchaseSuccess = "ご購入ありがとうございます！\nPro版の機能がアンロックされました。";
            MsgStartedInBackground = "バックグラウンドで起動しました。";
            MsgStartupDisabledByUser = "自動起動が Windows の設定またはタスクマネージャーによって無効化されています。\nWindows の「スタートアップ アプリ」設定を開いて Focus Dimmer を有効にしてください。";
            NavExclusions = "除外設定";
            NavGeneral = "一般設定";
            NavHotkeys = "ホットキー";
            NavMonitors = "モニター";
            NavPresets = "プリセット";
            NewPresetName = "新規プリセット";
            SearchPlaceholder = "プロセスを検索...";
            SubHeaderGeneral = "アプリの起動、動作、言語の設定です。";
            SubHeaderGlobalSettings = "これらの設定はすべてのモニターに適用されます。";
            SubHeaderHotkeys = "減光を素早く切り替えるキーボードショートカットを設定します。";
            SubHeaderLanguage = "表示言語を選択します";
            TitleColorPicker = "色の選択";
            TitleConfirm = "確認";
            TitleError = "エラー";
            TitleInspector = "Focus Dimmer インスペクター";
            TitleMigrationGuide = "移行ガイド";
            TitlePurchaseError = "購入エラー";
            TitleSelectAction = "アクションの選択";
            TitleSelectProcess = "アプリ選択";
            TitleSuccess = "成功";
            TooltipAddPreset = "現在の設定を新規プリセットとして保存";
            TooltipAlwaysDark = "他アプリのオーバーレイ(例: GeForce Experience)など、明るい領域の原因となるプロセスをここに追加してください。";
            TooltipDebugInspector = "マウス入力を透過する透明なウィンドウも含め、カーソル下の全ウィンドウを調査します。";
            TooltipDeletePreset = "選択したプリセットを削除";
            TooltipDimDesktopOnly = "デスクトップエリアのみが暗くなります。余白機能が無効になります。";
            TooltipDimEntirely = "他の明るくなるオプションより優先されます。";
            TooltipDimWhenIdle = "他の明るくなるオプションより優先されます。";
            TooltipEditPreset = "プリセット名を編集";
            TooltipLinkMonitors = "有効にすると、すべてのディスプレイの設定が同時に連動して変更されます。";
            TooltipSetAsDefault = "既定のプリセットに設定";
            TooltipWait = "ウィンドウがアクティブになってからアニメーションが開始されるまでの時間です。";
            WindowSelectApp = "アプリ選択";
        }

        public event PropertyChangedEventHandler? PropertyChanged;
        void OnProp([CallerMemberName] string? name = null) => PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(name));
    }
}
