<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>

		<UseWPF>true</UseWPF>
		<UseWindowsForms>true</UseWindowsForms>
		<ApplicationIcon>icon.ico</ApplicationIcon>
		<Platforms>AnyCPU;x64</Platforms>
		<Configurations>Debug;Release;Lite;Pro;LegacyPro</Configurations>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
	  <Optimize>True</Optimize>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
	  <Optimize>True</Optimize>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
	  <Optimize>True</Optimize>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
	  <Optimize>True</Optimize>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Lite|AnyCPU'">
		<Optimize>True</Optimize>
		<DefineConstants>$(DefineConstants);DEBUG</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Lite|x64'">
		<Optimize>True</Optimize>
		<DefineConstants>$(DefineConstants);DEBUG</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Pro|AnyCPU'">
		<Optimize>True</Optimize>
		<DefineConstants>$(DefineConstants);PRO_VERSION;DEBUG</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Pro|x64'">
		<Optimize>True</Optimize>
		<DefineConstants>$(DefineConstants);PRO_VERSION;DEBUG</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='LegacyPro|AnyCPU'">
		<Optimize>True</Optimize>
		<DefineConstants>$(DefineConstants);LEGACY_PRO;PRO_VERSION;DEBUG</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='LegacyPro|x64'">
		<Optimize>True</Optimize>
		<DefineConstants>$(DefineConstants);LEGACY_PRO;PRO_VERSION;DEBUG</DefineConstants>
	</PropertyGroup>

	<ItemGroup Condition="'$(Configuration)'!='LegacyPro'">
		<AppxManifest Include="Package.appxmanifest">
			<SubType>Designer</SubType>
		</AppxManifest>
	</ItemGroup>

	<ItemGroup Condition="'$(Configuration)'=='LegacyPro'">
		<AppxManifest Include="Package.Pro.appxmanifest">
			<SubType>Designer</SubType>
		</AppxManifest>
	</ItemGroup>

	<ItemGroup>
	  <None Remove="icon.ico" />
	</ItemGroup>

	<ItemGroup>
	  <Content Include="icon.ico">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Include="Languages\de.json">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Include="Languages\en.json">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Include="Languages\es.json">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Include="Languages\fr.json">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Include="Languages\ja.json">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Include="Languages\pt.json">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Include="Languages\zh.json">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>

</Project>